name: 'build prod-ready app'
inputs:
  webhook_url:
    description: The Mattermost webhook URL
    required: true
runs:
  using: composite
  steps:
    - name: Send loop notification
      uses: tferreira/matterfy@releases/v1
      if: (success() && github.ref == 'refs/heads/main') || failure()
      with:
        type: ${{ job.status }}
        job_name: 'Triggered by:  ${{ github.triggering_actor }}'
        url: 'https://dodobrands.loop.ru/hooks/rxwtrcc8cifuf8t9w6c1t41d3a'
